{
    "Audience": {
        "Secret": "my-secret-token-to-change-in-production",
        "Iss": "http://www.c-sharpcorner.com/members/catcher-wong",
        "Aud": "Infodation"
    },
    
    "eureka": {
        "client": {
            "serviceUrl": "http://localhost:8761/eureka/",
            "shouldRegisterWithEureka": true,
            "shouldFetchRegistry": true,
            "validateCertificates": false
        }
    }
}